### ISSUE TITLE
[Question]: How to Determine Which Version of AMBA Has Been Deployed

### ISSUE THREAD

**Issue by AErmie** [Azure/azure-monitor-baseline-alerts#550]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Question

### Description

We use a GitHub workflow/action to deploy the AMBA. In our workflow, we use an environment variable to control the version of AMBA that's being applied.

**Example:**

```yaml
name: Monitor Baseline Apply
# IMPORTANT: `name:` value needs to match the workflow file name exactly (though spaces can be replaced with hyphens)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: "true"
  Location: "canadacentral"
  ManagementGroupPrefix: "bcgov-managed-lz-forge"
  AMBA_VERSION: "2025-02-05"

jobs:
  deploy_job:
    name: AMBA Deploy (Release)
    runs-on: ubuntu-latest

<SNIP>

      - name: Azure CLI Deploy AMBA ARM Template
        id: deploy_amba
        shell: bash
        run: |
          az deployment \
            mg create \
            --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/${{ env.AMBA_VERSION }}/patterns/alz/alzArm.json \
            --location ${{ env.Location }} \
            --management-group-id ${{ env.ManagementGroupPrefix }} \
            --parameters ./azure_monitor_baseline_alerts/alzArm.param.json
```

While this works, it would be helpful to have some verification/validation in the Azure portal on what version has actually been applied in the environment. Something like a tag on the Alert Rules, etc. That way we're confident everything is being applied, and other team members don't accidently attempt to deploy an older version.

❓ Does this type of property exist anywhere?
