### ISSUE TITLE
[General workload suggestion]: ARM Deployment Equivalent to `terraform plan`

### ISSUE THREAD

**Issue by AErmie** [Azure/azure-monitor-baseline-alerts#628]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Other

### Description

Regardless of which Management Group hierarchy is used, most organizations have a need to see what will happen if they implement a tool or solution. 

For organizations that use Terraform, this is accomplished via `terraform plan`. However, up until recently, AMBA did not support Terraform for its deployment ([it does now though](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/HowTo/deploy/Deploy-with-Terraform/)).

I wanted to share our approach, when [deploying with GitHub Actions](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/HowTo/deploy/Deploy-with-GitHub-Actions/), to produce an equivalent of `terraform plan`.

We used the [sample workflow](https://github.com/Azure/azure-monitor-baseline-alerts/blob/main/patterns/alz/examples/sample-workflow.yml) file as a starting point, but modified it as follows.

**ARM What-If Output:**
We include the `what-if` parameter, and then output the results into a text file.

```yaml
name: Monitor Baseline Alerts (AMBA) Plan

on:
  workflow_dispatch:

  pull_request:
    paths:
      - azure_monitor_baseline_alerts/**
      - .github/workflows/monitor-baseline-pr.yaml
      - .github/workflows/monitor-baseline-apply.yaml

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: "true"
  Location: "canadacentral"
  ManagementGroupPrefix: "YOUR_MANAGEMENT_GROUP_NAME"
  AMBA_VERSION: "2025-04-04"

jobs:
  deploy_job:
    name: AMBA Deploy What-If (Release)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login via OIDC
        id: azure_login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Azure CLI What-If Deploy AMBA ARM Template
        id: deploy_amba
        shell: bash
        run: |
          az deployment mg what-if \
            --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/${{ env.AMBA_VERSION }}/patterns/alz/alzArm.json \
            --location ${{ env.Location }} \
            --management-group-id ${{ env.ManagementGroupPrefix }} \
            --parameters ./azure_monitor_baseline_alerts/alzArm.param.json | tee amba-what-if-output.txt
```

Then we add another step to parse the output from the file and group the results, adding it to the `$env:GITHUB_STEP_SUMMARY`, like so:

```yaml
- name: Parse What-If Output for Changes
  id: amba_changes
  shell: pwsh
  run: |
    # Get the content from the log file
    $content = Get-Content -Path "./amba-what-if-output.txt"

    # Define the patterns to search for and their corresponding messages
    $patternMessageMap = @{
      # Patterns for policies that will be added
      '\+ Microsoft\.Authorization/policyDefinitions/.*' = "Policies will be added:"
      '\+ Microsoft\.Authorization/policySetDefinitions/.*' = "Policy Sets will be added:"
      '\+ Microsoft\.Authorization/policyAssignments/.*' = "Policy Assignments will be added:"
      '\+ Microsoft\.Authorization/roleAssignments/.*' = "Role Assignments will be added:"

      # Patterns for policies that will be modified
      '~ Microsoft\.Authorization/policyDefinitions/.*' = "Policies will be modified:"
      '~ Microsoft\.Authorization/policySetDefinitions/.*' = "Policy Sets will be modified:"
      '~ Microsoft\.Authorization/policyAssignments/.*' = "Policy Assignments will be modified:"
      '~ Microsoft\.Authorization/roleAssignments/.*' = "Role Assignments will be modified:"

      # Patterns for policies that will be removed
      '- Microsoft\.Authorization/policyDefinitions/.*' = "Policies will be removed:"
      '- Microsoft\.Authorization/policySetDefinitions/.*' = "Policy Sets will be removed:"
      '- Microsoft\.Authorization/policyAssignments/.*' = "Policy Assignments will be removed:"
      '- Microsoft\.Authorization/roleAssignments/.*' = "Role Assignments will be removed:"
    }

    "# Azure Monitor Baseline Alerts (AMBA) What-If Summary" >> $env:GITHUB_STEP_SUMMARY
    "" >> $env:GITHUB_STEP_SUMMARY # this is a blank line

    # Iterate through each pattern in the map
    foreach ($pattern in $patternMessageMap.Keys) {
      # Use Select-String to find matches for the current pattern in the content
      $matches = $content | Select-String -Pattern $pattern
      if ($matches) {
        # Get the count of matches and output the message with the count
        $count = $matches.Count
        Write-Host "$count $($patternMessageMap[$pattern])"
        "## $count $($patternMessageMap[$pattern])" >> $env:GITHUB_STEP_SUMMARY
        '```' >> $env:GITHUB_STEP_SUMMARY

        # Process each match to remove the timestamp and write the clean line
        $matches | ForEach-Object {
          # Remove the timestamp using a regex pattern
          $cleanLine = $_.Line -replace '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z\s+', ''
          # Output the clean line
          Write-Output $cleanLine
          "$cleanLine" >> $env:GITHUB_STEP_SUMMARY
        }
        
        # Output a blank line for readability
        Write-Output ""
        '```' >> $env:GITHUB_STEP_SUMMARY
        "" >> $env:GITHUB_STEP_SUMMARY # this is a blank line
      }
    }
```

The end results is the equivalent of `terraform plan` for the ARM deployment, with a nice consolidated reference in the Action workflow.

![Image](https://github.com/user-attachments/assets/1f11e1e6-ffed-41b1-ae38-5a20ad77f978)

![Image](https://github.com/user-attachments/assets/595b0d01-6b0c-4930-b90f-918036493266)

Just thought I'd share, in case others might find it useful (or the AMBA team wants to include something similar in the deployment guides).
