### ISSUE TITLE
[General workload issue]: Terraform Deployment Method Does Not Support Targeted AMBA Release Deployments

### ISSUE THREAD

**Issue by AErmie** [Azure/azure-monitor-baseline-alerts#640]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Question

## 🐛 Problem
The [terraform](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/HowTo/deploy/Deploy-with-Terraform/) method of deploying AMBA does not support targeting a specific release version of AMBA for deployment.

## 📷 Screenshots
NA

## 👣 Repro steps
1. Compare the deployment steps for [GitHub Actions](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/HowTo/deploy/Deploy-with-GitHub-Actions/), [Azure PowerShell](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/HowTo/deploy/Deploy-with-Azure-PowerShell/), [Azure CLI](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/HowTo/deploy/Deploy-with-Azure-CLI/), etc. to the variables supported in the Terraform deployment

## 🤔 Expected
The Terraform deployment should support the same customizations as all other deployment methods, namely being able to deploy a specific release version of AMBA.

This would also require ensuring the [Update to New Release](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/HowTo/UpdateToNewReleases/) guide provides guidance for both ARM, and Terraform based deployments.

## ℹ️ Additional context
All other deployment methods allow you deploy a [specific release](https://github.com/Azure/azure-monitor-baseline-alerts/releases), based on targeting.

**Example GitHub Actions workflow:**
```yaml
env:
  AMBA_VERSION: "2025-04-04"

- name: Azure CLI Deploy AMBA ARM Template
  id: deploy_amba
  shell: bash
  run: |
    az deployment \
      mg create \
      --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/${{ env.AMBA_VERSION }}/patterns/alz/alzArm.json \
      --location ${{ env.Location }} \
      --management-group-id ${{ env.ManagementGroupPrefix }} \
      --parameters ./azure_monitor_baseline_alerts/alzArm.param.json
```

> [!NOTE]
> This is different from the **Azure Landing Zones Library** version ref in the `alz` provider:
> ```
> provider "alz" {
>  library_overwrite_enabled = true
>  library_references = [
>    {
>      path = "platform/amba"
>      ref  = "2025.04.0"
>    },
>    {
>      custom_url = "${path.root}/lib"
>    }
>  ]
>}
> ```

## 🙋‍♀️ Ask for the community
We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.
